TEMPORARY/Models/Lesson.cs
using Microsoft.Build.Framework;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace TEMPORARY.Models
{
    public partial class Lesson
    {
        public Lesson()
        {
            Exams = new HashSet<Exam>();
        }

        [DisplayName("Dərsin kodu")]
        public string LessonCode { get; set; } = null!;

        [DisplayName("Dərsin adı")]
        public string LessonName { get; set; } = null!;

        [DisplayName("Sinif")]
        public int Class { get; set; }

        [DisplayName("Müəllimin adı")]
        public string? TeacherName { get; set; }

        [DisplayName("Müəllimin soyadı")]
        public string? TeacherSurname { get; set; }

        public virtual ICollection<Exam> Exams { get; set; }
    }
}

TEMPORARY/Controllers/LessonController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TEMPORARY.Models;

namespace TEMPORARY.Controllers
{
    public class LessonController : Controller
    {
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly ExamDBContext _examDBContext;

        public LessonController(IHttpContextAccessor contextAccessor, ExamDBContext examDBContext)
        {
            _contextAccessor = contextAccessor;
            _examDBContext = examDBContext;
        }

        // GET: LessonController
        public async Task<ActionResult> Index()
        {
            var list = await _examDBContext.Lessons.AsNoTracking().ToListAsync();
            return View(list);
        }

        // GET: LessonController/Details
        public async Task<ActionResult> Details(string code)
        {
            if (code == null)
            {
                return NotFound();
            }

            var lesson = await _examDBContext.Lessons.FirstOrDefaultAsync(l => l.LessonCode == code);

            return View(lesson);
        }

        // GET: LessonController/AddLesson
        public ActionResult AddLesson()
        {
            return View();
        }

        // POST: LessonController/AddLesson
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddLesson(Lesson lesson)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _examDBContext.Lessons.AddAsync(lesson);
                    await _examDBContext.SaveChangesAsync();
                }
                else
                {
                    return View(lesson);
                }

                ModelState.Clear();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LessonController/EditLesson
        public async Task<IActionResult> EditLesson(string code)
        {
            var selectedLesson = await _examDBContext.Lessons.FirstOrDefaultAsync(l => l.LessonCode == code);
            if (selectedLesson == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(selectedLesson);
        }

        // POST: LessonController/EditLesson
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditLesson(Lesson lesson)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Lesson selected = new Lesson()
                    {
                        LessonCode = lesson.LessonCode,
                        LessonName = lesson.LessonName,
                        Class = lesson.Class,
                        TeacherName = lesson.TeacherName,
                        TeacherSurname = lesson.TeacherSurname
                    };

                    _examDBContext.Lessons.Update(selected);
                    await _examDBContext.SaveChangesAsync();
                }

                ModelState.Clear();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LessonController/DeleteLesson
        public async Task<ActionResult> DeleteLesson(string code)
        {
            if (string.IsNullOrEmpty(code))
            {
                return NotFound();
            }

            var lesson = await _examDBContext.Lessons.FirstOrDefaultAsync(l => l.LessonCode == code);
            if (lesson == null)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(lesson);
            }
        }

        // POST: LessonController/DeleteLesson
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteLesson(Lesson lesson)
        {
            try
            {
                var model = await _examDBContext.Lessons.FirstOrDefaultAsync(l=>l.LessonCode == lesson.LessonCode);
                _examDBContext.Lessons.Remove(model);
                await _examDBContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TEMPORARY/Views/Lesson/AddLesson.cshtml
@model Lesson
@{
    ViewData["Title"] = "AddLesson";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Yeni dərs əlavə et</h2>
    </div>

    <form method="POST" enctype="multipart/form-data" asp-controller="Lesson" asp-action="AddLesson">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="@Model.LessonCode">Dərsin kodu</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.LessonCode" placeholder="Dərsin kodunu daxil edin">
                <span asp-validation-for="@Model.LessonCode" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="@Model.LessonName">Dərsin adı</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.LessonName" placeholder="Dərsin adını daxil edin">
                <span asp-validation-for="@Model.LessonName" class="alert-danger"></span>
            </div>

            <div class="form-group col-md-6">
                <label asp-for="@Model.Class">Sinif</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.Class" placeholder="Sinifi daxil edin">
                <span asp-validation-for="@Model.Class" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="@Model.TeacherName">Müəlllimin adı</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.TeacherName" placeholder="Müəllimin adını daxil edin">
                <span asp-validation-for="@Model.TeacherName" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="@Model.TeacherSurname">Müəlllimin soyadı</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.TeacherSurname" placeholder="Müəlllimin soyadını daxil edin">
                <span asp-validation-for="@Model.TeacherSurname" class="alert-danger"></span>
            </div>
        </div>
        <input type="submit" class="btn btn-lg btn-success p-2" value="Təsdiqlə" />
    </form>
</div>

TEMPORARY/Views/Lesson/DeleteLesson.cshtml
@model Lesson
@{
    ViewData["Title"] = "Dərsi sil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Mövcud dərsi sil</h2>
    </div>

    <form method="POST" enctype="multipart/form-data" asp-controller="Lesson" asp-action="DeleteLesson">

        <div class="form-row">
            <div class="form-group col-md-6" hidden> 
                <label asp-for="@Model.LessonCode">Dərsin kodu</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.LessonCode" placeholder="Dərsin kodunu daxil edin" hidden>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="@Model.LessonName">Dərsin adı</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.LessonName" placeholder="Dərsin adını daxil edin" disabled>
            </div>

            <div class="form-group col-md-6">
                <label asp-for="@Model.Class">Sinif</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.Class" placeholder="Sinifi daxil edin" disabled>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="@Model.TeacherName">Müəlllimin adı</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.TeacherName" placeholder="Müəllimin adını daxil edin" disabled>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="@Model.TeacherSurname">Müəlllimin soyadı</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.TeacherSurname" placeholder="Müəlllimin soyadını daxil edin" disabled>
            </div>
        </div>
        <input type="submit" class="btn btn-lg btn-danger p-2" value="Sil" />
    </form>
</div>

TEMPORARY/Views/Lesson/Details.cshtml
@model Lesson
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<dt class="col-sm-2">
    </dt>
<dd class="col-sm-10">
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(m=>m.LessonName)</th>
            <th>@Html.DisplayNameFor(m=>m.Class)</th>
            <th>@Html.DisplayNameFor(m=>m.TeacherName)</th>
            <th>@Html.DisplayNameFor(m=>m.TeacherSurname)</th>
        </tr>

        <tr>
            <td>
                @Model.LessonName
            </td>
            <td>
                @Model.Class
            </td>
            <td>
                @Model.TeacherName
            </td>
            <td>
                @Model.TeacherSurname
            </td>
        </tr>

    </table>
</dd>

TEMPORARY/Views/Lesson/EditLesson.cshtml
@model Lesson
@{
    ViewData["Title"] = "Dərsi dəyiş";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Mövcud dərsi dəyiş</h2>
    </div>

    <form method="POST" enctype="multipart/form-data" asp-controller="Lesson" asp-action="EditLesson">

        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="@Model.LessonCode">Dərsin kodu</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.LessonCode" placeholder="Dərsin kodunu daxil edin">
                <span asp-validation-for="@Model.LessonCode" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="@Model.LessonName">Dərsin adı</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.LessonName" placeholder="Dərsin adını daxil edin">
                <span asp-validation-for="@Model.LessonName" class="alert-danger"></span>
            </div>

            <div class="form-group col-md-6">
                <label asp-for="@Model.Class">Sinif</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.Class" placeholder="Sinifi daxil edin">
                <span asp-validation-for="@Model.Class" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="@Model.TeacherName">Müəlllimin adı</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.TeacherName" placeholder="Müəllimin adını daxil edin">
                <span asp-validation-for="@Model.TeacherName" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="@Model.TeacherSurname">Müəlllimin soyadı</label>
                <input type="text" class="form-control mb-3" asp-for="@Model.TeacherSurname" placeholder="Müəlllimin soyadını daxil edin">
                <span asp-validation-for="@Model.TeacherSurname" class="alert-danger"></span>
            </div>
        </div>
        <input type="submit" class="btn btn-lg btn-success p-2" value="Təsdiqlə" />
    </form>
</div>

TEMPORARY/Views/Lesson/Index.cshtml
@model IEnumerable<Lesson>
@{
    ViewData["Title"] = "Dərslər";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <a class="text-center">
        <div class="container">
            <a asp-controller="Lesson" asp-action="AddLesson" class="btn btn-success">Yeni dərs yarat</a>
        </div>
        <br />
        <table class="table table-responsive bg-light">
            <thead>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.LessonCode)</td>
                    <td>@Html.DisplayNameFor(model => model.LessonName)</td>
                    <td>@Html.DisplayNameFor(model => model.Class)</td>
                    <td>@Html.DisplayNameFor(model => model.TeacherName)</td>
                    <td>@Html.DisplayNameFor(model => model.TeacherSurname)</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.LessonCode</td>
                        <td>@item.LessonName</td>
                        <td>@item.Class</td>
                        <td>@item.TeacherName</td>
                        <td>@item.TeacherSurname</td>
                        <td><a href="@Url.Action("Details","Lesson", new {code = item.LessonCode})">Ətraflı</a></td>
                        <td><a href="@Url.Action("EditLesson","Lesson", new {code = item.LessonCode})">Dəyiş</a></td>
                        <td><a href="@Url.Action("DeleteLesson","Lesson", new {code = item.LessonCode})">Sil</a></td>
                    </tr>
                }
            </tbody>
        </table>
</div>